(module
  (memory 1)
  (func (export "hot") (result i32)
    (local $v v128)
    (loop $L
      (local.set $v (i32x4.add (local.get $v) (local.get $v)))
      (local.set $v (i32x4.add (local.get $v) (local.get $v)))
      (local.set $v (i32x4.add (local.get $v) (local.get $v)))
      (local.set $v (i32x4.add (local.get $v) (local.get $v)))
      (local.set $v (i32x4.add (local.get $v) (local.get $v)))
      (local.set $v (i32x4.add (local.get $v) (local.get $v)))
      (local.set $v (i32x4.add (local.get $v) (local.get $v)))
      (local.set $v (i32x4.add (local.get $v) (local.get $v)))
      (local.set $v (i32x4.add (local.get $v) (local.get $v)))
      (local.set $v (i32x4.add (local.get $v) (local.get $v)))
      (local.set $v (i32x4.add (local.get $v) (local.get $v)))
      (local.set $v (i32x4.add (local.get $v) (local.get $v)))
      (local.set $v (i32x4.add (local.get $v) (local.get $v)))
      (local.set $v (i32x4.add (local.get $v) (local.get $v)))
      (local.set $v (i32x4.add (local.get $v) (local.get $v)))
      (local.set $v (i32x4.add (local.get $v) (local.get $v)))
    )
    (i32.const 0)
  )
)
